import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-black text-white`}>
        <header className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="text-xl font-semibold">
            Vicki Danielson Art
          </Link>
          <nav className="text-sm opacity-80">
            <Link href="/" className="hover:opacity-50">
              Gallery
            </Link>
            <span className="mx-3 select-none cursor-default">·</span>
            <Link href="/studio" className="hover:opacity-50">
              Studio
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
